/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_DOT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  aux_sym_data_types_token1 = 6,
  aux_sym_data_types_token2 = 7,
  aux_sym_data_types_token3 = 8,
  aux_sym_data_types_token4 = 9,
  aux_sym_data_types_token5 = 10,
  anon_sym_EQ = 11,
  sym_identifier = 12,
  sym_string = 13,
  sym_number = 14,
  sym_comment = 15,
  sym_kw_create = 16,
  sym_kw_table = 17,
  sym_kw_if = 18,
  aux_sym_kw_not_token1 = 19,
  sym_kw_primary = 20,
  sym_kw_key = 21,
  sym_kw_with = 22,
  sym_source_file = 23,
  sym__statement = 24,
  sym_create_table_statement = 25,
  sym_if_not_exists = 26,
  sym_table_name = 27,
  sym_column_definitions = 28,
  sym_column_definition = 29,
  sym_primary_key_inline = 30,
  sym_data_types = 31,
  sym_with_clause = 32,
  sym_table_option = 33,
  sym_literal = 34,
  sym_kw_not = 35,
  sym_kw_exists = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_column_definitions_repeat1 = 38,
  aux_sym_with_clause_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [aux_sym_data_types_token1] = "data_types_token1",
  [aux_sym_data_types_token2] = "data_types_token2",
  [aux_sym_data_types_token3] = "data_types_token3",
  [aux_sym_data_types_token4] = "data_types_token4",
  [aux_sym_data_types_token5] = "data_types_token5",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_kw_create] = "kw_create",
  [sym_kw_table] = "kw_table",
  [sym_kw_if] = "kw_if",
  [aux_sym_kw_not_token1] = "kw_not_token1",
  [sym_kw_primary] = "kw_primary",
  [sym_kw_key] = "kw_key",
  [sym_kw_with] = "kw_with",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_create_table_statement] = "create_table_statement",
  [sym_if_not_exists] = "if_not_exists",
  [sym_table_name] = "table_name",
  [sym_column_definitions] = "column_definitions",
  [sym_column_definition] = "column_definition",
  [sym_primary_key_inline] = "primary_key_inline",
  [sym_data_types] = "data_types",
  [sym_with_clause] = "with_clause",
  [sym_table_option] = "table_option",
  [sym_literal] = "literal",
  [sym_kw_not] = "kw_not",
  [sym_kw_exists] = "kw_exists",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_column_definitions_repeat1] = "column_definitions_repeat1",
  [aux_sym_with_clause_repeat1] = "with_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_data_types_token1] = aux_sym_data_types_token1,
  [aux_sym_data_types_token2] = aux_sym_data_types_token2,
  [aux_sym_data_types_token3] = aux_sym_data_types_token3,
  [aux_sym_data_types_token4] = aux_sym_data_types_token4,
  [aux_sym_data_types_token5] = aux_sym_data_types_token5,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_kw_create] = sym_kw_create,
  [sym_kw_table] = sym_kw_table,
  [sym_kw_if] = sym_kw_if,
  [aux_sym_kw_not_token1] = aux_sym_kw_not_token1,
  [sym_kw_primary] = sym_kw_primary,
  [sym_kw_key] = sym_kw_key,
  [sym_kw_with] = sym_kw_with,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_create_table_statement] = sym_create_table_statement,
  [sym_if_not_exists] = sym_if_not_exists,
  [sym_table_name] = sym_table_name,
  [sym_column_definitions] = sym_column_definitions,
  [sym_column_definition] = sym_column_definition,
  [sym_primary_key_inline] = sym_primary_key_inline,
  [sym_data_types] = sym_data_types,
  [sym_with_clause] = sym_with_clause,
  [sym_table_option] = sym_table_option,
  [sym_literal] = sym_literal,
  [sym_kw_not] = sym_kw_not,
  [sym_kw_exists] = sym_kw_exists,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_column_definitions_repeat1] = aux_sym_column_definitions_repeat1,
  [aux_sym_with_clause_repeat1] = aux_sym_with_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_data_types_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_create] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_table] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_kw_not_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_kw_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_key] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_with] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_create_table_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_not_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definitions] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_key_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_data_types] = {
    .visible = true,
    .named = true,
  },
  [sym_with_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_table_option] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_not] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_exists] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_column_definitions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_create = 1,
  field_name = 2,
  field_table = 3,
  field_table_name = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_create] = "create",
  [field_name] = "name",
  [field_table] = "table",
  [field_table_name] = "table_name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 3},
  [3] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 2},
  [3] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 3},
  [6] =
    {field_name, 0},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(49);
      ADVANCE_MAP(
        '\'', 1,
        '(', 52,
        ')', 54,
        ',', 53,
        '-', 5,
        '.', 51,
        '/', 2,
        ';', 50,
        '=', 60,
        'B', 32,
        'b', 32,
        'C', 34,
        'c', 34,
        'I', 19,
        'i', 19,
        'K', 13,
        'k', 13,
        'N', 31,
        'n', 31,
        'P', 35,
        'p', 35,
        'T', 6,
        't', 6,
        'U', 44,
        'u', 44,
        'W', 23,
        'w', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(66);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 13:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 17:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 18:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(69);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 20:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(73);
      END_STATE();
    case 21:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 24:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 28:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 29:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 31:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 36:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(70);
      END_STATE();
    case 40:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(20);
      END_STATE();
    case 41:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(9);
      END_STATE();
    case 43:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 45:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(41);
      END_STATE();
    case 46:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(72);
      END_STATE();
    case 47:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(71);
      END_STATE();
    case 48:
      if (eof) ADVANCE(49);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == ',') ADVANCE(53);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(50);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_data_types_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_data_types_token2);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_data_types_token3);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_data_types_token4);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_data_types_token5);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_kw_create);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_kw_table);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_kw_if);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_kw_not_token1);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_kw_primary);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_kw_key);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_kw_with);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 48},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 48},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 48},
  [10] = {.lex_state = 48},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 48},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 48},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 48},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 48},
  [32] = {.lex_state = 48},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 48},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 48},
  [45] = {.lex_state = 48},
  [46] = {.lex_state = 48},
  [47] = {.lex_state = 48},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_data_types_token1] = ACTIONS(1),
    [aux_sym_data_types_token2] = ACTIONS(1),
    [aux_sym_data_types_token3] = ACTIONS(1),
    [aux_sym_data_types_token4] = ACTIONS(1),
    [aux_sym_data_types_token5] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(1),
    [sym_kw_table] = ACTIONS(1),
    [sym_kw_if] = ACTIONS(1),
    [aux_sym_kw_not_token1] = ACTIONS(1),
    [sym_kw_primary] = ACTIONS(1),
    [sym_kw_key] = ACTIONS(1),
    [sym_kw_with] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(53),
    [sym__statement] = STATE(27),
    [sym_create_table_statement] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(11), 1,
      sym_column_definitions,
    STATE(43), 1,
      sym_with_clause,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [20] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(13), 1,
      sym_column_definitions,
    STATE(34), 1,
      sym_with_clause,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [40] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(8), 1,
      sym_data_types,
    ACTIONS(19), 5,
      aux_sym_data_types_token1,
      aux_sym_data_types_token2,
      aux_sym_data_types_token3,
      aux_sym_data_types_token4,
      aux_sym_data_types_token5,
  [54] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(5), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [69] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(26), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [82] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(5), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [97] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      sym_kw_primary,
    STATE(38), 1,
      sym_primary_key_inline,
    ACTIONS(34), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [111] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      sym_identifier,
    ACTIONS(40), 1,
      sym_kw_if,
    STATE(2), 1,
      sym_table_name,
    STATE(37), 1,
      sym_if_not_exists,
  [127] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(44), 1,
      anon_sym_RPAREN,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(20), 1,
      sym_column_definition,
  [143] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(41), 1,
      sym_with_clause,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(35), 1,
      sym_with_clause,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [181] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
  [216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_identifier,
    STATE(7), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [227] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [249] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_column_definitions_repeat1,
  [262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    STATE(33), 2,
      sym__statement,
      sym_create_table_statement,
  [273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_kw_primary,
  [291] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_column_definition,
  [304] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_column_definitions_repeat1,
  [317] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(32), 1,
      sym_literal,
    ACTIONS(79), 2,
      sym_string,
      sym_number,
  [328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
  [341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_column_definition,
  [363] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_column_definitions_repeat1,
  [376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [394] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      aux_sym_kw_not_token1,
    STATE(42), 1,
      sym_kw_not,
  [428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      sym_identifier,
    STATE(3), 1,
      sym_table_name,
  [438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_kw_not_token1,
    STATE(47), 1,
      sym_kw_exists,
  [480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [488] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(40), 1,
      sym_column_definition,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_identifier,
  [505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_identifier,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      aux_sym_kw_not_token1,
  [526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
  [533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_kw_key,
  [540] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_EQ,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_kw_table,
  [554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 69,
  [SMALL_STATE(7)] = 82,
  [SMALL_STATE(8)] = 97,
  [SMALL_STATE(9)] = 111,
  [SMALL_STATE(10)] = 127,
  [SMALL_STATE(11)] = 143,
  [SMALL_STATE(12)] = 157,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 181,
  [SMALL_STATE(15)] = 194,
  [SMALL_STATE(16)] = 203,
  [SMALL_STATE(17)] = 216,
  [SMALL_STATE(18)] = 227,
  [SMALL_STATE(19)] = 240,
  [SMALL_STATE(20)] = 249,
  [SMALL_STATE(21)] = 262,
  [SMALL_STATE(22)] = 273,
  [SMALL_STATE(23)] = 282,
  [SMALL_STATE(24)] = 291,
  [SMALL_STATE(25)] = 304,
  [SMALL_STATE(26)] = 317,
  [SMALL_STATE(27)] = 328,
  [SMALL_STATE(28)] = 341,
  [SMALL_STATE(29)] = 350,
  [SMALL_STATE(30)] = 363,
  [SMALL_STATE(31)] = 376,
  [SMALL_STATE(32)] = 385,
  [SMALL_STATE(33)] = 394,
  [SMALL_STATE(34)] = 402,
  [SMALL_STATE(35)] = 410,
  [SMALL_STATE(36)] = 418,
  [SMALL_STATE(37)] = 428,
  [SMALL_STATE(38)] = 438,
  [SMALL_STATE(39)] = 446,
  [SMALL_STATE(40)] = 454,
  [SMALL_STATE(41)] = 462,
  [SMALL_STATE(42)] = 470,
  [SMALL_STATE(43)] = 480,
  [SMALL_STATE(44)] = 488,
  [SMALL_STATE(45)] = 498,
  [SMALL_STATE(46)] = 505,
  [SMALL_STATE(47)] = 512,
  [SMALL_STATE(48)] = 519,
  [SMALL_STATE(49)] = 526,
  [SMALL_STATE(50)] = 533,
  [SMALL_STATE(51)] = 540,
  [SMALL_STATE(52)] = 547,
  [SMALL_STATE(53)] = 554,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 3, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 2, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 5, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_types, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_option, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 6, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 3, 0, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_inline, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_exists, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_not_exists, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_not, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [120] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cql3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cql3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
