/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  sym_string = 3,
  sym_number = 4,
  anon_sym_DOT = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  aux_sym_data_types_token1 = 9,
  aux_sym_data_types_token2 = 10,
  aux_sym_data_types_token3 = 11,
  aux_sym_data_types_token4 = 12,
  aux_sym_data_types_token5 = 13,
  anon_sym_EQ = 14,
  sym_comment = 15,
  sym_kw_create = 16,
  sym_kw_table = 17,
  sym_kw_if = 18,
  sym_kw_not = 19,
  sym_kw_exists = 20,
  sym_kw_primary = 21,
  sym_kw_key = 22,
  sym_kw_with = 23,
  sym_kw_clustering = 24,
  sym_kw_order = 25,
  sym_kw_by = 26,
  sym_kw_asc = 27,
  sym_kw_desc = 28,
  sym_kw_id = 29,
  sym_kw_and = 30,
  sym_source_file = 31,
  sym__statement = 32,
  sym_literal = 33,
  sym_create_table_statement = 34,
  sym_if_not_exists = 35,
  sym_table_name = 36,
  sym_column_definitions = 37,
  sym_column_definition = 38,
  sym_primary_key_inline = 39,
  sym_primary_key_definition = 40,
  sym_partition_keys_definition = 41,
  sym_clustering_keys_definition = 42,
  sym_data_types = 43,
  sym_with_clause = 44,
  sym_table_option = 45,
  sym_clustering_order_by_clause = 46,
  sym_id_clause = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_column_definitions_repeat1 = 49,
  aux_sym_partition_keys_definition_repeat1 = 50,
  aux_sym_clustering_keys_definition_repeat1 = 51,
  aux_sym_with_clause_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [aux_sym_data_types_token1] = "data_types_token1",
  [aux_sym_data_types_token2] = "data_types_token2",
  [aux_sym_data_types_token3] = "data_types_token3",
  [aux_sym_data_types_token4] = "data_types_token4",
  [aux_sym_data_types_token5] = "data_types_token5",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [sym_kw_create] = "kw_create",
  [sym_kw_table] = "kw_table",
  [sym_kw_if] = "kw_if",
  [sym_kw_not] = "kw_not",
  [sym_kw_exists] = "kw_exists",
  [sym_kw_primary] = "kw_primary",
  [sym_kw_key] = "kw_key",
  [sym_kw_with] = "kw_with",
  [sym_kw_clustering] = "kw_clustering",
  [sym_kw_order] = "kw_order",
  [sym_kw_by] = "kw_by",
  [sym_kw_asc] = "kw_asc",
  [sym_kw_desc] = "kw_desc",
  [sym_kw_id] = "kw_id",
  [sym_kw_and] = "kw_and",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_literal] = "literal",
  [sym_create_table_statement] = "create_table_statement",
  [sym_if_not_exists] = "if_not_exists",
  [sym_table_name] = "table_name",
  [sym_column_definitions] = "column_definitions",
  [sym_column_definition] = "column_definition",
  [sym_primary_key_inline] = "primary_key_inline",
  [sym_primary_key_definition] = "primary_key_definition",
  [sym_partition_keys_definition] = "partition_keys_definition",
  [sym_clustering_keys_definition] = "clustering_keys_definition",
  [sym_data_types] = "data_types",
  [sym_with_clause] = "with_clause",
  [sym_table_option] = "table_option",
  [sym_clustering_order_by_clause] = "clustering_order_by_clause",
  [sym_id_clause] = "id_clause",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_column_definitions_repeat1] = "column_definitions_repeat1",
  [aux_sym_partition_keys_definition_repeat1] = "partition_keys_definition_repeat1",
  [aux_sym_clustering_keys_definition_repeat1] = "clustering_keys_definition_repeat1",
  [aux_sym_with_clause_repeat1] = "with_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_data_types_token1] = aux_sym_data_types_token1,
  [aux_sym_data_types_token2] = aux_sym_data_types_token2,
  [aux_sym_data_types_token3] = aux_sym_data_types_token3,
  [aux_sym_data_types_token4] = aux_sym_data_types_token4,
  [aux_sym_data_types_token5] = aux_sym_data_types_token5,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [sym_kw_create] = sym_kw_create,
  [sym_kw_table] = sym_kw_table,
  [sym_kw_if] = sym_kw_if,
  [sym_kw_not] = sym_kw_not,
  [sym_kw_exists] = sym_kw_exists,
  [sym_kw_primary] = sym_kw_primary,
  [sym_kw_key] = sym_kw_key,
  [sym_kw_with] = sym_kw_with,
  [sym_kw_clustering] = sym_kw_clustering,
  [sym_kw_order] = sym_kw_order,
  [sym_kw_by] = sym_kw_by,
  [sym_kw_asc] = sym_kw_asc,
  [sym_kw_desc] = sym_kw_desc,
  [sym_kw_id] = sym_kw_id,
  [sym_kw_and] = sym_kw_and,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_literal] = sym_literal,
  [sym_create_table_statement] = sym_create_table_statement,
  [sym_if_not_exists] = sym_if_not_exists,
  [sym_table_name] = sym_table_name,
  [sym_column_definitions] = sym_column_definitions,
  [sym_column_definition] = sym_column_definition,
  [sym_primary_key_inline] = sym_primary_key_inline,
  [sym_primary_key_definition] = sym_primary_key_definition,
  [sym_partition_keys_definition] = sym_partition_keys_definition,
  [sym_clustering_keys_definition] = sym_clustering_keys_definition,
  [sym_data_types] = sym_data_types,
  [sym_with_clause] = sym_with_clause,
  [sym_table_option] = sym_table_option,
  [sym_clustering_order_by_clause] = sym_clustering_order_by_clause,
  [sym_id_clause] = sym_id_clause,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_column_definitions_repeat1] = aux_sym_column_definitions_repeat1,
  [aux_sym_partition_keys_definition_repeat1] = aux_sym_partition_keys_definition_repeat1,
  [aux_sym_clustering_keys_definition_repeat1] = aux_sym_clustering_keys_definition_repeat1,
  [aux_sym_with_clause_repeat1] = aux_sym_with_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_data_types_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_create] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_table] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_if] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_not] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_key] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_with] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_clustering] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_order] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_by] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_asc] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_id] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_and] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_create_table_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_not_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definitions] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_key_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_key_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_partition_keys_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_clustering_keys_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_data_types] = {
    .visible = true,
    .named = true,
  },
  [sym_with_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_table_option] = {
    .visible = true,
    .named = true,
  },
  [sym_clustering_order_by_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_id_clause] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_column_definitions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_partition_keys_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clustering_keys_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_clustering_key = 1,
  field_create = 2,
  field_name = 3,
  field_partition_key = 4,
  field_table = 5,
  field_table_name = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_clustering_key] = "clustering_key",
  [field_create] = "create",
  [field_name] = "name",
  [field_partition_key] = "partition_key",
  [field_table] = "table",
  [field_table_name] = "table_name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 3},
  [3] = {.index = 6, .length = 2},
  [4] = {.index = 8, .length = 1},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 1},
  [11] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 2},
  [3] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 3},
  [6] =
    {field_name, 0},
    {field_type, 1},
  [8] =
    {field_partition_key, 0},
  [9] =
    {field_partition_key, 1},
  [10] =
    {field_clustering_key, 0},
  [11] =
    {field_partition_key, 1},
    {field_partition_key, 2, .inherited = true},
  [13] =
    {field_partition_key, 0, .inherited = true},
    {field_partition_key, 1, .inherited = true},
  [15] =
    {field_clustering_key, 0},
    {field_clustering_key, 1, .inherited = true},
  [17] =
    {field_clustering_key, 1},
  [18] =
    {field_clustering_key, 0, .inherited = true},
    {field_clustering_key, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\'', 1,
        '(', 11,
        ')', 13,
        ',', 12,
        '-', 5,
        '.', 10,
        '/', 2,
        ';', 7,
        '=', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'A', 1,
        'a', 1,
        'B', 2,
        'b', 2,
        'C', 3,
        'c', 3,
        'D', 4,
        'd', 4,
        'E', 5,
        'e', 5,
        'I', 6,
        'i', 6,
        'K', 7,
        'k', 7,
        'N', 8,
        'n', 8,
        'O', 9,
        'o', 9,
        'P', 10,
        'p', 10,
        'T', 11,
        't', 11,
        'U', 12,
        'u', 12,
        'W', 13,
        'w', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(14);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(16);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(18);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(22);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(23);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(29);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_kw_by);
      END_STATE();
    case 18:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 19:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(39);
      END_STATE();
    case 21:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_kw_id);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_kw_if);
      END_STATE();
    case 24:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 25:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(46);
      END_STATE();
    case 30:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(50);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_kw_and);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_kw_asc);
      END_STATE();
    case 36:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_data_types_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_kw_key);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_kw_not);
      END_STATE();
    case 44:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(64);
      END_STATE();
    case 53:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_kw_desc);
      END_STATE();
    case 55:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 57:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 58:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_data_types_token2);
      END_STATE();
    case 60:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(70);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_data_types_token3);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_kw_with);
      END_STATE();
    case 63:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 64:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_kw_order);
      END_STATE();
    case 68:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_kw_table);
      END_STATE();
    case 70:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(76);
      END_STATE();
    case 71:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 72:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_kw_create);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_kw_exists);
      END_STATE();
    case 75:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(79);
      END_STATE();
    case 76:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_data_types_token4);
      END_STATE();
    case 78:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_kw_primary);
      END_STATE();
    case 80:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(82);
      END_STATE();
    case 81:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 82:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 83:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_data_types_token5);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_kw_clustering);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_data_types_token1] = ACTIONS(1),
    [aux_sym_data_types_token2] = ACTIONS(1),
    [aux_sym_data_types_token3] = ACTIONS(1),
    [aux_sym_data_types_token4] = ACTIONS(1),
    [aux_sym_data_types_token5] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(1),
    [sym_kw_table] = ACTIONS(1),
    [sym_kw_if] = ACTIONS(1),
    [sym_kw_not] = ACTIONS(1),
    [sym_kw_exists] = ACTIONS(1),
    [sym_kw_primary] = ACTIONS(1),
    [sym_kw_key] = ACTIONS(1),
    [sym_kw_with] = ACTIONS(1),
    [sym_kw_clustering] = ACTIONS(1),
    [sym_kw_order] = ACTIONS(1),
    [sym_kw_by] = ACTIONS(1),
    [sym_kw_asc] = ACTIONS(1),
    [sym_kw_desc] = ACTIONS(1),
    [sym_kw_id] = ACTIONS(1),
    [sym_kw_and] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(94),
    [sym__statement] = STATE(23),
    [sym_create_table_statement] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(17), 1,
      sym_column_definitions,
    STATE(66), 1,
      sym_with_clause,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [20] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(15), 1,
      sym_column_definitions,
    STATE(56), 1,
      sym_with_clause,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [40] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_kw_clustering,
    ACTIONS(23), 1,
      sym_kw_id,
    STATE(18), 3,
      sym_table_option,
      sym_clustering_order_by_clause,
      sym_id_clause,
  [58] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(20), 1,
      sym_data_types,
    ACTIONS(25), 5,
      aux_sym_data_types_token1,
      aux_sym_data_types_token2,
      aux_sym_data_types_token3,
      aux_sym_data_types_token4,
      aux_sym_data_types_token5,
  [72] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_kw_clustering,
    ACTIONS(23), 1,
      sym_kw_id,
    STATE(38), 3,
      sym_table_option,
      sym_clustering_order_by_clause,
      sym_id_clause,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_DOT,
    ACTIONS(27), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [103] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 1,
      sym_kw_primary,
    STATE(54), 1,
      sym_column_definition,
    STATE(55), 1,
      sym_primary_key_definition,
  [122] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_kw_primary,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_column_definition,
    STATE(61), 1,
      sym_primary_key_definition,
  [141] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(51), 2,
      sym__statement,
      sym_create_table_statement,
  [155] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_kw_if,
    STATE(3), 1,
      sym_table_name,
    STATE(69), 1,
      sym_if_not_exists,
  [171] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(51), 2,
      sym__statement,
      sym_create_table_statement,
  [185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(51), 2,
      sym__statement,
      sym_create_table_statement,
  [199] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym_column_definition,
  [215] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(57), 1,
      sym_with_clause,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [239] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_kw_with,
    STATE(58), 1,
      sym_with_clause,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [253] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_kw_and,
    STATE(19), 1,
      aux_sym_with_clause_repeat1,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [267] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_kw_and,
    STATE(21), 1,
      aux_sym_with_clause_repeat1,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_kw_primary,
    STATE(53), 1,
      sym_primary_key_inline,
    ACTIONS(67), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_kw_and,
    STATE(21), 1,
      aux_sym_with_clause_repeat1,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [318] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_SEMI,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
  [331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_kw_primary,
  [349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    STATE(51), 2,
      sym__statement,
      sym_create_table_statement,
  [373] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_column_definitions_repeat1,
  [386] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(37), 1,
      sym_literal,
    ACTIONS(88), 2,
      sym_string,
      sym_number,
  [397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
  [410] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(97), 1,
      sym_kw_primary,
    STATE(59), 1,
      sym_primary_key_definition,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_column_definitions_repeat1,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_and,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_and,
  [472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_and,
  [481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_and,
  [490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
  [503] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_partition_keys_definition,
  [516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_column_definitions_repeat1,
  [538] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_partition_keys_definition_repeat1,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [560] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_partition_keys_definition_repeat1,
  [573] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_and,
  [595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_partition_keys_definition_repeat1,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_COMMA,
  [676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(158), 1,
      anon_sym_COMMA,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
  [728] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(54), 1,
      sym_column_definition,
  [738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [746] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      sym_kw_asc,
      sym_kw_desc,
  [764] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [772] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(88), 1,
      sym_clustering_keys_definition,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [790] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(2), 1,
      sym_table_name,
  [800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [808] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_identifier,
  [839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym_kw_order,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_identifier,
  [853] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
  [860] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_LPAREN,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_kw_exists,
  [874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_kw_key,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_EQ,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_EQ,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_kw_by,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_string,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym_kw_table,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_identifier,
  [958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_kw_not,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym_identifier,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_identifier,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_kw_key,
  [993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 90,
  [SMALL_STATE(8)] = 103,
  [SMALL_STATE(9)] = 122,
  [SMALL_STATE(10)] = 141,
  [SMALL_STATE(11)] = 155,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 199,
  [SMALL_STATE(15)] = 215,
  [SMALL_STATE(16)] = 229,
  [SMALL_STATE(17)] = 239,
  [SMALL_STATE(18)] = 253,
  [SMALL_STATE(19)] = 267,
  [SMALL_STATE(20)] = 281,
  [SMALL_STATE(21)] = 295,
  [SMALL_STATE(22)] = 309,
  [SMALL_STATE(23)] = 318,
  [SMALL_STATE(24)] = 331,
  [SMALL_STATE(25)] = 340,
  [SMALL_STATE(26)] = 349,
  [SMALL_STATE(27)] = 362,
  [SMALL_STATE(28)] = 373,
  [SMALL_STATE(29)] = 386,
  [SMALL_STATE(30)] = 397,
  [SMALL_STATE(31)] = 410,
  [SMALL_STATE(32)] = 423,
  [SMALL_STATE(33)] = 432,
  [SMALL_STATE(34)] = 441,
  [SMALL_STATE(35)] = 454,
  [SMALL_STATE(36)] = 463,
  [SMALL_STATE(37)] = 472,
  [SMALL_STATE(38)] = 481,
  [SMALL_STATE(39)] = 490,
  [SMALL_STATE(40)] = 503,
  [SMALL_STATE(41)] = 516,
  [SMALL_STATE(42)] = 525,
  [SMALL_STATE(43)] = 538,
  [SMALL_STATE(44)] = 551,
  [SMALL_STATE(45)] = 560,
  [SMALL_STATE(46)] = 573,
  [SMALL_STATE(47)] = 586,
  [SMALL_STATE(48)] = 595,
  [SMALL_STATE(49)] = 608,
  [SMALL_STATE(50)] = 621,
  [SMALL_STATE(51)] = 634,
  [SMALL_STATE(52)] = 642,
  [SMALL_STATE(53)] = 650,
  [SMALL_STATE(54)] = 658,
  [SMALL_STATE(55)] = 666,
  [SMALL_STATE(56)] = 676,
  [SMALL_STATE(57)] = 684,
  [SMALL_STATE(58)] = 692,
  [SMALL_STATE(59)] = 700,
  [SMALL_STATE(60)] = 710,
  [SMALL_STATE(61)] = 718,
  [SMALL_STATE(62)] = 728,
  [SMALL_STATE(63)] = 738,
  [SMALL_STATE(64)] = 746,
  [SMALL_STATE(65)] = 756,
  [SMALL_STATE(66)] = 764,
  [SMALL_STATE(67)] = 772,
  [SMALL_STATE(68)] = 782,
  [SMALL_STATE(69)] = 790,
  [SMALL_STATE(70)] = 800,
  [SMALL_STATE(71)] = 808,
  [SMALL_STATE(72)] = 816,
  [SMALL_STATE(73)] = 824,
  [SMALL_STATE(74)] = 832,
  [SMALL_STATE(75)] = 839,
  [SMALL_STATE(76)] = 846,
  [SMALL_STATE(77)] = 853,
  [SMALL_STATE(78)] = 860,
  [SMALL_STATE(79)] = 867,
  [SMALL_STATE(80)] = 874,
  [SMALL_STATE(81)] = 881,
  [SMALL_STATE(82)] = 888,
  [SMALL_STATE(83)] = 895,
  [SMALL_STATE(84)] = 902,
  [SMALL_STATE(85)] = 909,
  [SMALL_STATE(86)] = 916,
  [SMALL_STATE(87)] = 923,
  [SMALL_STATE(88)] = 930,
  [SMALL_STATE(89)] = 937,
  [SMALL_STATE(90)] = 944,
  [SMALL_STATE(91)] = 951,
  [SMALL_STATE(92)] = 958,
  [SMALL_STATE(93)] = 965,
  [SMALL_STATE(94)] = 972,
  [SMALL_STATE(95)] = 979,
  [SMALL_STATE(96)] = 986,
  [SMALL_STATE(97)] = 993,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 3, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 2, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 6, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_types, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_clause, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_option, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 7, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clustering_keys_definition, 1, 0, 6),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clustering_order_by_clause, 7, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 8), SHIFT_REPEAT(84),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 8),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clustering_keys_definition, 2, 0, 9),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 11), SHIFT_REPEAT(93),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 11),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 10),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 3, 0, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 6, 0, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_inline, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 1, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_definition, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 3, 0, 5),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 5),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 4, 0, 7),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_definition, 7, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [224] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_not_exists, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cql3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cql3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
