/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_DOT = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  aux_sym_data_types_token1 = 7,
  aux_sym_data_types_token2 = 8,
  aux_sym_data_types_token3 = 9,
  aux_sym_data_types_token4 = 10,
  aux_sym_data_types_token5 = 11,
  anon_sym_EQ = 12,
  sym_string = 13,
  sym_number = 14,
  sym_comment = 15,
  sym_kw_create = 16,
  sym_kw_table = 17,
  sym_kw_if = 18,
  sym_kw_not = 19,
  sym_kw_exists = 20,
  sym_kw_primary = 21,
  sym_kw_key = 22,
  sym_kw_with = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_create_table_statement = 26,
  sym_if_not_exists = 27,
  sym_table_name = 28,
  sym_column_definitions = 29,
  sym_column_definition = 30,
  sym_primary_key_definition = 31,
  sym_partition_keys_definition = 32,
  sym_clustering_keys_definition = 33,
  sym_primary_key_inline = 34,
  sym_data_types = 35,
  sym_with_clause = 36,
  sym_table_option = 37,
  sym_literal = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_column_definitions_repeat1 = 40,
  aux_sym_partition_keys_definition_repeat1 = 41,
  aux_sym_clustering_keys_definition_repeat1 = 42,
  aux_sym_with_clause_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [aux_sym_data_types_token1] = "data_types_token1",
  [aux_sym_data_types_token2] = "data_types_token2",
  [aux_sym_data_types_token3] = "data_types_token3",
  [aux_sym_data_types_token4] = "data_types_token4",
  [aux_sym_data_types_token5] = "data_types_token5",
  [anon_sym_EQ] = "=",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_kw_create] = "kw_create",
  [sym_kw_table] = "kw_table",
  [sym_kw_if] = "kw_if",
  [sym_kw_not] = "kw_not",
  [sym_kw_exists] = "kw_exists",
  [sym_kw_primary] = "kw_primary",
  [sym_kw_key] = "kw_key",
  [sym_kw_with] = "kw_with",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_create_table_statement] = "create_table_statement",
  [sym_if_not_exists] = "if_not_exists",
  [sym_table_name] = "table_name",
  [sym_column_definitions] = "column_definitions",
  [sym_column_definition] = "column_definition",
  [sym_primary_key_definition] = "primary_key_definition",
  [sym_partition_keys_definition] = "partition_keys_definition",
  [sym_clustering_keys_definition] = "clustering_keys_definition",
  [sym_primary_key_inline] = "primary_key_inline",
  [sym_data_types] = "data_types",
  [sym_with_clause] = "with_clause",
  [sym_table_option] = "table_option",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_column_definitions_repeat1] = "column_definitions_repeat1",
  [aux_sym_partition_keys_definition_repeat1] = "partition_keys_definition_repeat1",
  [aux_sym_clustering_keys_definition_repeat1] = "clustering_keys_definition_repeat1",
  [aux_sym_with_clause_repeat1] = "with_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_data_types_token1] = aux_sym_data_types_token1,
  [aux_sym_data_types_token2] = aux_sym_data_types_token2,
  [aux_sym_data_types_token3] = aux_sym_data_types_token3,
  [aux_sym_data_types_token4] = aux_sym_data_types_token4,
  [aux_sym_data_types_token5] = aux_sym_data_types_token5,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_kw_create] = sym_kw_create,
  [sym_kw_table] = sym_kw_table,
  [sym_kw_if] = sym_kw_if,
  [sym_kw_not] = sym_kw_not,
  [sym_kw_exists] = sym_kw_exists,
  [sym_kw_primary] = sym_kw_primary,
  [sym_kw_key] = sym_kw_key,
  [sym_kw_with] = sym_kw_with,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_create_table_statement] = sym_create_table_statement,
  [sym_if_not_exists] = sym_if_not_exists,
  [sym_table_name] = sym_table_name,
  [sym_column_definitions] = sym_column_definitions,
  [sym_column_definition] = sym_column_definition,
  [sym_primary_key_definition] = sym_primary_key_definition,
  [sym_partition_keys_definition] = sym_partition_keys_definition,
  [sym_clustering_keys_definition] = sym_clustering_keys_definition,
  [sym_primary_key_inline] = sym_primary_key_inline,
  [sym_data_types] = sym_data_types,
  [sym_with_clause] = sym_with_clause,
  [sym_table_option] = sym_table_option,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_column_definitions_repeat1] = aux_sym_column_definitions_repeat1,
  [aux_sym_partition_keys_definition_repeat1] = aux_sym_partition_keys_definition_repeat1,
  [aux_sym_clustering_keys_definition_repeat1] = aux_sym_clustering_keys_definition_repeat1,
  [aux_sym_with_clause_repeat1] = aux_sym_with_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_data_types_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_types_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_create] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_table] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_if] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_not] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_key] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_with] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_create_table_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_not_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definitions] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_key_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_partition_keys_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_clustering_keys_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_key_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_data_types] = {
    .visible = true,
    .named = true,
  },
  [sym_with_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_table_option] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_column_definitions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_partition_keys_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clustering_keys_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_with_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_clustering_key = 1,
  field_create = 2,
  field_name = 3,
  field_partition_key = 4,
  field_table = 5,
  field_table_name = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_clustering_key] = "clustering_key",
  [field_create] = "create",
  [field_name] = "name",
  [field_partition_key] = "partition_key",
  [field_table] = "table",
  [field_table_name] = "table_name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 3},
  [3] = {.index = 6, .length = 2},
  [4] = {.index = 8, .length = 1},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 1},
  [11] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 2},
  [3] =
    {field_create, 0},
    {field_table, 1},
    {field_table_name, 3},
  [6] =
    {field_name, 0},
    {field_type, 1},
  [8] =
    {field_partition_key, 0},
  [9] =
    {field_partition_key, 1},
  [10] =
    {field_clustering_key, 0},
  [11] =
    {field_partition_key, 1},
    {field_partition_key, 2, .inherited = true},
  [13] =
    {field_partition_key, 0, .inherited = true},
    {field_partition_key, 1, .inherited = true},
  [15] =
    {field_clustering_key, 0},
    {field_clustering_key, 1, .inherited = true},
  [17] =
    {field_clustering_key, 1},
  [18] =
    {field_clustering_key, 0, .inherited = true},
    {field_clustering_key, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\'', 1,
        '(', 9,
        ')', 11,
        ',', 10,
        '-', 5,
        '.', 8,
        '/', 2,
        ';', 7,
        '=', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'B', 1,
        'b', 1,
        'C', 2,
        'c', 2,
        'E', 3,
        'e', 3,
        'I', 4,
        'i', 4,
        'K', 5,
        'k', 5,
        'N', 6,
        'n', 6,
        'P', 7,
        'p', 7,
        'T', 8,
        't', 8,
        'U', 9,
        'u', 9,
        'W', 10,
        'w', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(14);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(19);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_kw_if);
      END_STATE();
    case 15:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_data_types_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_kw_key);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_kw_not);
      END_STATE();
    case 30:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_data_types_token2);
      END_STATE();
    case 42:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(50);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_data_types_token3);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_kw_with);
      END_STATE();
    case 45:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 46:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_kw_table);
      END_STATE();
    case 50:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(55);
      END_STATE();
    case 51:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_kw_create);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_kw_exists);
      END_STATE();
    case 54:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(57);
      END_STATE();
    case 55:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_data_types_token4);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_kw_primary);
      END_STATE();
    case 58:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_data_types_token5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_data_types_token1] = ACTIONS(1),
    [aux_sym_data_types_token2] = ACTIONS(1),
    [aux_sym_data_types_token3] = ACTIONS(1),
    [aux_sym_data_types_token4] = ACTIONS(1),
    [aux_sym_data_types_token5] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(1),
    [sym_kw_table] = ACTIONS(1),
    [sym_kw_if] = ACTIONS(1),
    [sym_kw_not] = ACTIONS(1),
    [sym_kw_exists] = ACTIONS(1),
    [sym_kw_primary] = ACTIONS(1),
    [sym_kw_key] = ACTIONS(1),
    [sym_kw_with] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(68),
    [sym__statement] = STATE(23),
    [sym_create_table_statement] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_kw_create] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(15), 1,
      sym_data_types,
    ACTIONS(11), 5,
      aux_sym_data_types_token1,
      aux_sym_data_types_token2,
      aux_sym_data_types_token3,
      aux_sym_data_types_token4,
      aux_sym_data_types_token5,
  [14] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_kw_with,
    STATE(14), 1,
      sym_column_definitions,
    STATE(60), 1,
      sym_with_clause,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [34] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_kw_with,
    STATE(11), 1,
      sym_column_definitions,
    STATE(50), 1,
      sym_with_clause,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [54] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(8), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [69] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(25), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [82] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 1,
      sym_kw_primary,
    STATE(45), 1,
      sym_column_definition,
    STATE(46), 1,
      sym_primary_key_definition,
  [101] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(8), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [116] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_kw_primary,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_column_definition,
    STATE(52), 1,
      sym_primary_key_definition,
  [135] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(46), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_column_definition,
  [151] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_kw_with,
    STATE(48), 1,
      sym_with_clause,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_kw_with,
  [175] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(54), 1,
      sym_kw_if,
    STATE(4), 1,
      sym_table_name,
    STATE(47), 1,
      sym_if_not_exists,
  [191] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_kw_with,
    STATE(49), 1,
      sym_with_clause,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_kw_primary,
    STATE(43), 1,
      sym_primary_key_inline,
    ACTIONS(58), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [228] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_kw_create,
    STATE(63), 2,
      sym__statement,
      sym_create_table_statement,
  [239] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_column_definitions_repeat1,
  [252] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(5), 2,
      sym_table_option,
      aux_sym_with_clause_repeat1,
  [263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_kw_primary,
  [281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(35), 1,
      aux_sym_source_file_repeat1,
  [294] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      aux_sym_source_file_repeat1,
  [307] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_column_definitions_repeat1,
  [320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(32), 1,
      sym_literal,
    ACTIONS(76), 2,
      sym_string,
      sym_number,
  [331] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    STATE(35), 1,
      aux_sym_source_file_repeat1,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [353] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_RPAREN,
    ACTIONS(82), 1,
      sym_kw_primary,
    STATE(56), 1,
      sym_primary_key_definition,
  [366] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [375] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_column_definitions_repeat1,
  [388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_partition_keys_definition,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [428] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      aux_sym_source_file_repeat1,
  [441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      aux_sym_partition_keys_definition_repeat1,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_kw_with,
  [463] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_partition_keys_definition_repeat1,
  [476] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [489] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_partition_keys_definition_repeat1,
  [502] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [515] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_clustering_keys_definition_repeat1,
  [528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    ACTIONS(134), 1,
      anon_sym_COMMA,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(3), 1,
      sym_table_name,
  [572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [588] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [604] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
  [614] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(45), 1,
      sym_column_definition,
  [624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [632] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      anon_sym_COMMA,
  [652] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
    STATE(73), 1,
      sym_clustering_keys_definition,
  [662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_identifier,
  [725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_kw_not,
  [732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_kw_key,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
  [746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_identifier,
  [753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
  [760] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_kw_exists,
  [767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_kw_key,
  [774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
  [781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_kw_table,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
  [795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
  [802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_identifier,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
  [816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_identifier,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_EQ,
  [830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 69,
  [SMALL_STATE(7)] = 82,
  [SMALL_STATE(8)] = 101,
  [SMALL_STATE(9)] = 116,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 151,
  [SMALL_STATE(12)] = 165,
  [SMALL_STATE(13)] = 175,
  [SMALL_STATE(14)] = 191,
  [SMALL_STATE(15)] = 205,
  [SMALL_STATE(16)] = 219,
  [SMALL_STATE(17)] = 228,
  [SMALL_STATE(18)] = 239,
  [SMALL_STATE(19)] = 252,
  [SMALL_STATE(20)] = 263,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 281,
  [SMALL_STATE(23)] = 294,
  [SMALL_STATE(24)] = 307,
  [SMALL_STATE(25)] = 320,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 344,
  [SMALL_STATE(28)] = 353,
  [SMALL_STATE(29)] = 366,
  [SMALL_STATE(30)] = 375,
  [SMALL_STATE(31)] = 388,
  [SMALL_STATE(32)] = 397,
  [SMALL_STATE(33)] = 406,
  [SMALL_STATE(34)] = 419,
  [SMALL_STATE(35)] = 428,
  [SMALL_STATE(36)] = 441,
  [SMALL_STATE(37)] = 454,
  [SMALL_STATE(38)] = 463,
  [SMALL_STATE(39)] = 476,
  [SMALL_STATE(40)] = 489,
  [SMALL_STATE(41)] = 502,
  [SMALL_STATE(42)] = 515,
  [SMALL_STATE(43)] = 528,
  [SMALL_STATE(44)] = 536,
  [SMALL_STATE(45)] = 544,
  [SMALL_STATE(46)] = 552,
  [SMALL_STATE(47)] = 562,
  [SMALL_STATE(48)] = 572,
  [SMALL_STATE(49)] = 580,
  [SMALL_STATE(50)] = 588,
  [SMALL_STATE(51)] = 596,
  [SMALL_STATE(52)] = 604,
  [SMALL_STATE(53)] = 614,
  [SMALL_STATE(54)] = 624,
  [SMALL_STATE(55)] = 632,
  [SMALL_STATE(56)] = 642,
  [SMALL_STATE(57)] = 652,
  [SMALL_STATE(58)] = 662,
  [SMALL_STATE(59)] = 670,
  [SMALL_STATE(60)] = 678,
  [SMALL_STATE(61)] = 686,
  [SMALL_STATE(62)] = 694,
  [SMALL_STATE(63)] = 702,
  [SMALL_STATE(64)] = 710,
  [SMALL_STATE(65)] = 718,
  [SMALL_STATE(66)] = 725,
  [SMALL_STATE(67)] = 732,
  [SMALL_STATE(68)] = 739,
  [SMALL_STATE(69)] = 746,
  [SMALL_STATE(70)] = 753,
  [SMALL_STATE(71)] = 760,
  [SMALL_STATE(72)] = 767,
  [SMALL_STATE(73)] = 774,
  [SMALL_STATE(74)] = 781,
  [SMALL_STATE(75)] = 788,
  [SMALL_STATE(76)] = 795,
  [SMALL_STATE(77)] = 802,
  [SMALL_STATE(78)] = 809,
  [SMALL_STATE(79)] = 816,
  [SMALL_STATE(80)] = 823,
  [SMALL_STATE(81)] = 830,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 3, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_with_clause, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_with_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 4, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 2, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 6, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_types, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_column_definitions_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_option, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definitions, 7, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clustering_keys_definition, 1, 0, 6),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 8), SHIFT_REPEAT(69),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 8),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clustering_keys_definition, 2, 0, 9),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 11), SHIFT_REPEAT(77),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 11),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 3, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clustering_keys_definition_repeat1, 2, 0, 10),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 5, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_table_statement, 6, 0, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_inline, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 1, 0, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_definition, 5, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 3, 0, 5),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_partition_keys_definition_repeat1, 2, 0, 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partition_keys_definition, 4, 0, 7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_key_definition, 7, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [174] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_not_exists, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cql3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cql3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
